### ISSUE TITLE
Default date is Oct 4, 2018

### ISSUE THREAD

**Issue by danieldevalk** [xxhomey19/nba-bar#10]
Upon clicking on the menu bar item, the first thing it shows is information for the date Oct 4, 2018. Clicking the arrows to go to the current date doesn't correct this behavior, even after quitting and reopening.

**Comment by xxhomey19** [comment]
Thanks @danieldevalk 
I noticed this bug as well. Will fix it tomorrow :)

**Comment by danieldevalk** [comment]
it works great! thanks for fixing :-) love the app

**Comment by xxhomey19** [comment]
@danieldevalk Sorry I found some bugs today so please upgrade to v1.2.2 😅

**Comment by xxhomey19** [comment]
Everything works fine now
