### ISSUE TITLE
Schedule dates are off

### ISSUE THREAD

**Issue by GentryRiggen** [xxhomey19/nba-bar#2]
The games in the following screenshot were on April 20th, 2018, not April 21st. My computer is set to Mountain timezone if that helps.

<img width="671" alt="screen shot 2018-04-20 at 8 12 29 pm" src="https://user-images.githubusercontent.com/6298523/39079405-40136fc8-44d7-11e8-8238-d6f757b47298.png">

**Comment by xxhomey19** [comment]
Hi @GentryRiggen 

Could you show me `Date.now()` in your computer? The date logic is written in [here](https://github.com/xxhomey19/nba-bar/blob/master/src/utils/getApiDate.js). It seems to me that getting the timestamp of **the start of a day for `Date.now()`** first, then turn it to New York timezone, finally get the start of a day of that timestamp which should be the correct date for APIs.
 
Take my computer as an example. My computer is set to Taipei timezone which is +8:00, and today is April 21st, 2018.
In this case, 
1. my `date.now()` is `1524279400207`
2. `startOfDay(date.now())` is `Sat Apr 21 2018 00:00:00 GMT+0800`
3. its New York timestamp is `2018-04-20T00:00:00-04:00`

Eventually I get `1524196800000`, then I use it as API date argument. It means that I get game schedule on April 20th, and that is correct for me.

In the nut shell, I will write a unit test for this function, and use your `Date.now()` to check whether the date result is correct.

**Comment by GentryRiggen** [comment]
<img width="739" alt="screen shot 2018-04-21 at 1 51 52 pm" src="https://user-images.githubusercontent.com/6298523/39088217-4ccb99b8-456b-11e8-867c-9c4c018f84fe.png">

**Comment by xxhomey19** [comment]
@GentryRiggen 
I just release v1.0.1. Please let me know it solves the issue.

**Comment by xxhomey19** [comment]
It works fine now.
